version: "3.8"

services:
    mariadb:
        image: mariadb:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_HOST: "%"
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"

volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./docker/data
